### ISSUE TITLE
对163.com过滤规则不足

### ISSUE THREAD

**Issue by iyee** [cjx82630/cjxlist#1]
现在Safari上用的uBlock，订阅 `CHN: China: cjxlist (main focus on Chinese sites)‎ (raw.githubusercontent.com)` 后网易的网站上只清理了部分广告，看了下至少 `g.163.com` 域没处理，相对来说EasyList China就已经过滤得很清爽，可以参考一下。。

**Comment by cjx82630** [comment]
原cjxlist由CJX在2014.1.3发布，作为ChinaList的补充列表。在2014.3.21停止维护。现在地址的内容是EasyList的精简版.具体看
http://abpchina.org/forum/forum.php?mod=viewthread&tid=29667

2015-02-25 18:07 GMT+08:00 Yeè <notifications@github.com>:

**Comment by iyee** [comment]
精简版也是可以继续加上有效的处理规则吧。。
