### ISSUE TITLE
Would you want to add a licence to your lists/repo?

### ISSUE THREAD

**Issue by DandelionSprout** [cjx82630/cjxlist#19]
I've simply noticed that your list doesn't have an open-source licence, meaning that it's technically still using "All Rights Reserved".

If you were to want to add one, but you're confused as to which one to choose, we can divide them into two categories: Loose licences, and strict licences.

Loose licences usually say *"You can do whatever you want with my list, just don't blame me if things go wrong, and it's nicely appreciated if you credit me."* This includes MIT, BSD-3, Unlicense, CC-0, Dandelicence, WTFPL, and Public Domain, among others.

Strict licences usually say *"You can only use this list on my terms. You must only use it in open-source projects, you must credit me in a specific way, and in some cases you can't use it in paid projects."* This includes GPLv3, LGPLv3, CC BY-NC-SA, Mozilla Public License, and Apache 2.0.

**Comment by cjx82630** [comment]
Thanks. LGPLv3 Added.
