### ISSUE TITLE
关于「自我推广」规则

### ISSUE THREAD

**Issue by waldens** [cjx82630/cjxlist#2]
屏蔽「自我推广」广告的规则，除了
https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt
网上还有其它规则互补吗？

因为c大这个自用规则，仍有漏网之鱼，而且还不少呢（当然能理解，无苛责之意，别误会）。例如百度云的自我推广：
![](http://ww3.sinaimg.cn/large/88e10423gw1es7lt54w8ej20tc0axwgf.jpg)
还有163邮箱的等等，都没有包括进去。虽然能自行加EHH，不过还是想问问，有没有齐全点儿的规则。

**Comment by cjx82630** [comment]
其它规则不清楚.cjx-annoyance.txt主要处理"太烦人"的自我推广. 比如弹窗,遮挡类. 不太烦人的话, 可处理或不处理.你所说的网站我再看看.
