### ISSUE TITLE
rtys520.com 未过滤广告 背后注意/NSFW

### ISSUE THREAD

**Issue by Yuki2718** [cjx82630/cjxlist#20]
Hi, I thought you also maintain EL China so I hope reporting here will be accepted, I don't know how to use the official EL China forum.

**Issue**
The title URL is an example - these NSFW sites deliver the same or similar unblocked ads:
```
llzw889.com
gogosns.com
xazs8.com
```

<details>

![rtys520](https://user-images.githubusercontent.com/58900598/94154923-5a8fcd80-feb9-11ea-9be4-66ccba04a444.png)

</details>

They're called from similarly named scripts such as:
```
/dbhf.js
/sbhf.js
/xbhf.js
```
There are more patterns though.

**Environment**
Firefox 80.0.1 + uBlock Origin 1.29.2 (default + EL China + CJX)

**Comment by cjx82630** [comment]
Fixed
