### ISSUE TITLE
[NSFW][18+]草榴的关闭abp能屏蔽吗?

### ISSUE THREAD

**Issue by foxdodo** [cjx82630/cjxlist#26]
https://www.t66y.com/htm_data/2101/2/4277143.html
链接需要翻墙, 每次打开草榴任意页面都会有10s提示关闭广告屏蔽插件

**Comment by cjx82630** [comment]
你可以点ABP图标,在t66y禁用ABP,然后安装脚本 https://greasyfork.org/zh-CN/scripts/383142-t66y-com
