### ISSUE TITLE
为什么不开启github pages服务

### ISSUE THREAD

**Issue by fxqy** [cjx82630/cjxlist#27]
国内githubusercontent.com根本无法访问，开启github pages服务，扩展可以直接连

**Comment by qpzr** [comment]
> 国内githubusercontent.com根本无法访问，开启github pages服务，扩展可以直接连

https://gitee.com/cjx82630/cjxlist 你们村刚通网吗

**Comment by fxqy** [comment]
回复晚了，刚通网。
看这盛气凌人的样子，你也是刚小人得志不久，还要再接再厉啊👍



在 2021-02-05 03:08:00，"qpzr" ***@***.***> 写道：

国内githubusercontent.com根本无法访问，开启github pages服务，扩展可以直接连

https://gitee.com/cjx82630/cjxlist 你们村刚通网吗
