### ISSUE TITLE
误过滤索尼官网图片

### ISSUE THREAD

**Issue by LisonFan** [cjx82630/cjxlist#30]
https://www.sonystyle.com.cn/products/bravia/index.html

uBlock Origin
使用的 CJX's Annoyance List

开启前：
![image](https://user-images.githubusercontent.com/9424775/120256904-be2c8f00-c2c1-11eb-9369-afe5c06ba6d8.png)

开启后：
![image](https://user-images.githubusercontent.com/9424775/120256923-c7b5f700-c2c1-11eb-9b82-b7a3af8c62c1.png)

**Comment by sr093906** [comment]
@@||ntalker.com^$script,domain=www.sonystyle.com.cn

**Comment by cjx82630** [comment]
Fixed.
