### ISSUE TITLE
掘金更换域名

### ISSUE THREAD

**Issue by shenzhiming88** [cjx82630/cjxlist#33]
您好！
掘金域名更换成了`juejin.cn`，是否需要把这两行改一下呢？
https://github.com/cjx82630/cjxlist/blob/8449fa880091fc6d9f80d0b210722cfa02040f32/cjx-annoyance.txt#L683
https://github.com/cjx82630/cjxlist/blob/8449fa880091fc6d9f80d0b210722cfa02040f32/cjx-annoyance.txt#L1277

**Comment by cjx82630** [comment]
没触发
