### ISSUE TITLE
qb.zuoyebang.com

### ISSUE THREAD

**Issue by shenzhiming88** [cjx82630/cjxlist#34]
您好！
`https://qb.zuoyebang.com/xfe-question/question/58d3999e32c66c898a71677d99ee0686.html`
应该属于自我推广
![image](https://user-images.githubusercontent.com/66902050/127742710-737d7b96-d68c-4e69-8d56-b842991c2b48.png)
并且点击`更多答案(1)`时，会出现如图所示的弹窗
![2021-07-31_22-19-35](https://user-images.githubusercontent.com/66902050/127742750-40ccc487-d354-460f-bef3-34f1c58274e9.gif)
谢谢！

**Comment by krystian3w** [comment]
https://github.com/uBlockOrigin/uAssets/issues/9926

**Comment by cjx82630** [comment]
[Added the filters.](3872ef4688c06b0ccd506162571af9503c5e5079)
please add subscription(ABP icon,Preferences,Advanced) https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

**Comment by krystian3w** [comment]
This link works too in uBlock Origin / AdGuard (but Gitlab team banned use in `github.com` - needed is create `github.io` hosting):

https://subscribe.adblockplus.org/?location=https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt&title=CN%20AdList
