### ISSUE TITLE
segmentfault.com

### ISSUE THREAD

**Issue by krystian3w** [cjx82630/cjxlist#40]
### What happens/happend:

After scroll on first visit we have fake pop-up with recommended logon

### URL-s:

```
https://segmentfault.com/q/1010000003115620
https://segmentfault.com/q/1010000009476561
```

### My CSS/Extended CSS styles solution:

```css
segmentfault.com##.modal:has-text(你知道吗？)
segmentfault.com##.modal-backdrop:has(~ .modal:has-text(你知道吗？))
segmentfault.com##.modal-open:style(overflow: auto !important; padding-right: 0 !important;)
segmentfault.com##.modal-open [style]:is([data-padding-right], [data-margin-right]):style(padding-right: 0 !important; margin-right: 0 !important;)
```

* The weirdest self is navigating with the attributes `[data-padding-right]`/`[data-margin-right]` - firstly I see as combo for `modal-open` pop-ups.

* `你知道吗` we can change to better detection fake pop-up

* ExtendedCSS is optional for `.modal-backdrop` - cut for all pop-ups is not big fail

* To cover older browsers possible convert `is` to: `.modal-open [style][data-padding-right], .modal-open [style][data-margin-right]` 
Also will works faster if latest `:is` have lags similar to experminental implemenetation as `-moz-any`/`-webkit-any` (`:matches`/`:any`)

Also follow: https://github.com/DandelionSprout/adfilt/issues/581

**Comment by cjx82630** [comment]
If not going to log in , maybe try this `segmentfault.com#$#abort-on-property-read g_useSSR`

**Comment by cjx82630** [comment]
The solution is fantastic. But some sites may require users to log in for some reason. I usually don't block the popup.

**Comment by krystian3w** [comment]
But real login can work as long touched by aopr on g_useSSR.

This is only annoying modal with "show motto".
