### ISSUE TITLE
封鎖過多

### ISSUE THREAD

**Issue by a77841s** [cjx82630/cjxlist#42]
### 列出存在问题的网址 List the website(s) you're having issues:

https://www.mobile01.com/topicdetail.php?f=297&t=6193097

### 什么问题 What happens?

封鎖太多，小惡魔新聞台也是推薦相關的並且是站內的貼文，不該封鎖才對..

### 列出你启用的列表 List Subscriptions you're using:

ABP filters

CJX's Annoyance List

CPBL Filters for ABP & uBO

EasyList

Easylist Cookie List

EasyPrivacy

Fanboy's Notifications Blocking List

Fanboy's problematic-sites

Fanboy's Social Blocking List

I don't care about cookies

NoCoin Filter List

Spam404

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 10 21h2
- 浏览器/版本 Browser/version: Edge 103.0.1264.77
- 过滤工具/版本 Adblock Extension/version: Adblock Plus 3.14.1

**Comment by cjx82630** [comment]
30分钟后更新试试
Fixed.Please manually update in 30 minutes.
