### ISSUE TITLE
未去除白塊，影響過濾後網站整體美觀

### ISSUE THREAD

**Issue by a77841s** [cjx82630/cjxlist#43]
### 列出存在问题的网址 List the website(s) you're having issues:

https://www.mobile01.com/topicdetail.php?f=296&t=6609932

### 什么问题 What happens?

右邊上方白塊封鎖廣告後未去除，留白一塊影響網站整體美觀

### 列出你启用的列表 List Subscriptions you're using:

ABP filters

CJX's Annoyance List

CPBL Filters for ABP & uBO

EasyList China+EasyList

EasyPrivacy

Fanboy's Notifications Blocking List

Fanboy's Social Blocking List

I don't care about cookies

NoCoin Filter List

Spam404

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 10 21h2
- 浏览器/版本 Browser/version: Edge 104.0.1293.54
- 过滤工具/版本 Adblock Extension/version: Adblock Plus 3.14.1

### 附注(列出有问题的规则,截图,建议等) Other details:

提取Adguard Chinese規則建議新增

ltn.com.tw,ctwant.com,mobile01.com##div[id^="_popIn_recommend"]
storm.mg,mobile01.com##div[id^="dablewidget_"]

此二條規則，已經過實測可去除頁面殘餘白塊問題。

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes.

**Comment by a77841s** [comment]
是否可以再幫忙補上一條
m.mobile01.com##.u-ad-image
規則

用於去除手機版的白塊呢？
謝謝大大

**Comment by cjx82630** [comment]
30分钟后更新 
Fixed.Please manually update in 30 minutes.

**Comment by a77841s** [comment]
cjx大大您好，我是否可以此帖作往後提交去除網頁白塊的回覆呢？
若不斷發文我怕造成洗版。

一個小說網站，手機版內容的白塊去除規則
m.hetubook.com##[class="m1"]
