### ISSUE TITLE
虎牙未开播的直播间会自动播放视频广告

### ISSUE THREAD

**Issue by Heporis** [cjx82630/cjxlist#48]
### 列出存在问题的网址 List the website(s) you're having issues:
比如：https://www.huya.com/yuno1202

### 什么问题 What happens?
自动播放垃圾游戏的视频广告

### 附注(列出有问题的规则,截图,建议等) Other details:
![image](https://user-images.githubusercontent.com/51895154/229991428-6e3f37d1-5493-4601-8a0f-6ad73f87ec38.png)
希望能阻止加载这个视频，谢谢

**Comment by cjx82630** [comment]
如果你用ubo adg, 试试自定义`||huya.com/leaf/*=vodadv&$redirect=noop-0.1s.mp3,domain=huya.com`
