### ISSUE TITLE
这个规则会导致百度贴吧  看帖组到精品组的加载问题 要刷新才能出现帖子

### ISSUE THREAD

**Issue by ICMYS** [cjx82630/cjxlist#5]
RT 是CJX's Annoyance List

**Comment by ICMYS** [comment]
不知道是不是和Easylist China规则混用的缘故 但只要添加了这个规则 贴吧就会有如题的bug 两个页面的切换必须要刷新

**Comment by cjx82630** [comment]
fixed. 160806
