### ISSUE TITLE
CJX's EasyList Lite 導致 智冠科技 網頁顯示異常

### ISSUE THREAD

**Issue by tkp206093** [cjx82630/cjxlist#50]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.soft-world.com/Home

### 什么问题 What happens?
開啟了之後會導致智冠科技網頁無法正常排列顯示

### 列出你启用的列表 List Subscriptions you're using:
CJX's EasyList Lite

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 11 專業版 22H2 22621.1635
- 浏览器/版本 Browser/version: Microsoft Edge 版本 112.0.1722.68 (官方組建) (64 位元)
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.49.2

### 附注(列出有问题的规则,截图,建议等) Other details:
<img width="1607" alt="image" src="https://user-images.githubusercontent.com/29872453/236058062-4eca359c-a471-4dc9-8d08-4c5be3c67509.png">

**Comment by cjx82630** [comment]
CJX's EasyList Lite是英文列表的缩小版, 现在都是大内存强cpu, 不需要使用了, 请使用其他英文列表, 如Easylist
