### ISSUE TITLE
zoosnet.net 和 zoossoft.cn

### ISSUE THREAD

**Issue by ZoosnetRunner** [cjx82630/cjxlist#51]
### 列出存在问题的网址 List the website(s) you're having issues:
zoosnet.net
zoossoft.cn

### 什么问题 What happens?
您好，我们的域名在屏蔽名单中了。我们的域名是提供在线实时对话服务的，不是广告~

### 列出你启用的列表 List Subscriptions you're using:
cjxlist

### 你的设置 Your settings
- 系统/版本 OS/version: 
- 浏览器/版本 Browser/version: 
- 过滤工具/版本 Adblock Extension/version: 

### 附注(列出有问题的规则,截图,建议等) Other details:
我们的域名是提供在线咨询服务的，并非广告。还请您帮忙把我们的域名从屏蔽列表中移除。
如果是其他原因导致的，烦请您也把原因告诉我哦，我们将全力配合整改
![issuepic](https://github.com/cjx82630/cjxlist/assets/138740678/d555a103-4c68-4546-b3b1-6518f5dd8a5f)

**Comment by cjx82630** [comment]
cjxlist不是官方列表, 而是个人列表. 个人列表全凭个人喜好, 而且不会被默认订阅和启用.

**Comment by ZoosnetRunner** [comment]
> cjxlist不是官方列表, 而是个人列表. 个人列表全凭个人喜好, 而且不会被默认订阅和启用.

对不起啊，我确实不懂，这之前也没上过GITHUB，感觉您这个列表使用的人还是挺多的，我看到有人也在推荐使用这个列表，影响力还是挺大的。
另外能否请您教教我，官方列表去哪里反馈呢？我在这里转了1天转懵了

**Comment by cjx82630** [comment]
只有刻意的寻找才会订阅这个人列表, 影响其实不大. 这是中文官方列表的[反馈网址](https://github.com/easylist/easylistchina/issues), 官方列表没有包含你所列的域名.

**Comment by ZoosnetRunner** [comment]
> 只有刻意的寻找才会订阅这个人列表, 影响其实不大. 这是中文官方列表的[反馈网址](https://github.com/easylist/easylistchina/issues), 官方列表没有包含你所列的域名.

好嘞，谢谢您~
