### ISSUE TITLE
Permission to use the Annoyance List in the Wipr app

### ISSUE THREAD

**Issue by rongpengli** [cjx82630/cjxlist#58]
### 什么问题 What happens?

Can the annoyance list be used in the Wipr app? The one-purchase, non-open-source app is sold on Mac AppStore at https://apps.apple.com/us/app/wipr/id1030595027. Thanks very much. The app alone does not support to subscribe a list manually. But the author of the Wipr app can add it once gets the permission.

Annoyance List 能否在非开源的Wipr应用中授权使用，相关应用一次性付费，但不具备订阅链接功能。如获得授权，软件开发者可以添加该链接，以提升去广告能力。谢谢。

**Comment by Crystal-RainSlide** [comment]
Author of Wipr: @mipstian
