### ISSUE TITLE
B站首页非广告误屏蔽

### ISSUE THREAD

**Issue by GOOD-AN** [cjx82630/cjxlist#59]
### 列出存在问题的网址 List the website(s) you're having issues:
https://www.bilibili.com/

### 什么问题 What happens?
首页非广告元素误屏蔽

### 列出你启用的列表 List Subscriptions you're using:
CJX's Annoyance List

### 你的设置 Your settings
- 系统/版本 OS/version: Windows 10 22H2
- 浏览器/版本 Browser/version: Microsoft Edge 131.0.2903.99
- 过滤工具/版本 Adblock Extension/version: uBlock Origin 1.61.2

### 附注(列出有问题的规则,截图,建议等) Other details:
启用前
![image](https://github.com/user-attachments/assets/5d922762-0f41-4e9f-a2c2-5de45da10289)
启用后
![image](https://github.com/user-attachments/assets/4645da00-2d76-4c04-a9c6-f6d88fa6ce0e)
目前观测到的是` .is-rcmd > div:only-child`下的`a`标签`href`为`cm.bilibili.com/cm/api/fees`

**Comment by cjx82630** [comment]
https://github.com/cjx82630/cjxlist/commit/5a5cc5aadb2ec80e27dad91d4041d04edfdb432b
